Name=lliurex-cssh
Name[es]=Gestión remota de clientes.
Name[qcv]=Gestió remota de clients.
Comment=Administració remota de clients
Comment[es]=Administración remota de clientes
Comment[qcv]=Administració remota de clients
Icon=lliurex-cssh
Groups=teachers;admin;admins;sudo
Category=Network
ScriptPath=lliurex-cssh.zmd
Using=pkexec
Service=False
